services:
  - type: web
    name: portfolio-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: DB_USE_SSL
        value: "true"
      - key: SSL_CA_PATH
        value: "ca.pem"
